---
driver:
  forward_agent: yes
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.0

transport:
  name: winrm

platforms:
  - name: windows-8.1-professional
    driver:
      box: windows-8.1
  #- name: windows2008r2
    #driver:
      #box: win2008r2
  #- name: windows2012r2
    #driver:
      #box: kensykora/windows_2012_r2_standard

suites:
  - name: default
    run_list:
      - recipe[windows::default]
